{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# jupyter notebook\n",
    "---\n",
    "1. [安装Anaconda](https://www.anaconda.com/), 安装好Anaconda后，打开Anaconda, 点击安装jupyter notebook\n",
    "2. 运行，网页查看效果，默认地址：*http://localhost:8888*\n",
    "3. 设置jupyter notebook主题[GitHub jupyter notebook themes](https://github.com/dunovank/jupyter-themes)  \n",
    "```\n",
    "pip install jupyterthemes\n",
    "pip install --upgrade jupyterthemes\n",
    "```\n",
    "4. chesterish主题设置  \n",
    "查看主题：jt -l  \n",
    "设置主题：jt -t chesterish -T  \n",
    "恢复默认主题：jt -r  \n",
    "5. 对默认的工作路径进行修改，首先我们打开anaconda cmd窗口，然后执行命令 jupyter notebook --generate-config,在用户目录下找到.jupyter文件，并打开，修改notebook_dir这个值为需要的工作路径实际值。\n",
    "6. 常用快捷键  \n",
    "你需要查看菜单栏上的help-keyboard shortcuts，包含了最新的快捷键列表。另外可以用ctrl+shift+p组合键，能调出search框，哪里不会搜哪里。  \n",
    "run：Ctrl+enter  \n",
    "edit mode：enter  \n",
    "exit edit mode(enter command mode):Esc  \n",
    "insert cell below:b  \n",
    "insert cell above:a  \n",
    "delete cell:dd  \n",
    "\n",
    "在一个cell中（在command模式下）\n",
    "\n",
    "1. 按下 y, 进入Code;\n",
    "\n",
    "2. 按下m, 进入Markdown;\n",
    "7. 在notebook和code中切换  \n",
    "在command模式下按下 y, 进入Code;按下m, 进入Markdown;  \n",
    "# markdown  \n",
    "---\n",
    "*jupyter notebook自带，不需要单独安装，简单介绍一下常用的语法*  \n",
    "+ 推荐一款编辑器[typora](https://www.typora.io/#)  \n",
    "+ 标题：#，##，##\n",
    "+ 无序列表：+，-，*\n",
    "+ 有序列表：罗马数字+英文句号，比如：1. ，2. ，\n",
    "+ 分割线：行首三个以上的-，*，中间可以加空格，但是不可以有其它字符\n",
    "+ 换行：连续两个空格+回车  \n",
    "+ 不转义Markdown语法：用代码块的符号，在esc下面的那个键  \n",
    "+ 行首缩进1个全角字符：`&emsp`;  \n",
    "+ &emsp;检查是否真的缩进了1个字符  \n",
    "+ &emsp;&emsp;检查是否真的缩进了两个字符  \n",
    "+ 引用:>\n",
    ">一级引用\n",
    ">>二级引用  \n",
    "\n",
    "+ 代码块：一行代码“`”,多行代码三个“`”开始和结束  \n",
    "`import os`  \n",
    "```\n",
    "pip install jupyterthemes\n",
    "pip install --upgrade jupyterthemes\n",
    "```\n",
    "+ 链接：[This link](http://example.NET/) has no title attribute.\n",
    "+ 插入图片：\n",
    "![插入图片URL]() \n",
    "# 公式编辑器：LaTex  \n",
    "---\n",
    "1.单行公式：$s=\\pi*r^2$   \n",
    "2.行间公式：$$r=\\pi*r^2$$\n",
    "3.公式中的希腊字母：反斜杠+字母，`\\alpha`，$\\alpha$  \n",
    "4.开方：$y=\\sqrt{x^2+x^4}+\\sqrt[4]{x^3}$  \n",
    "5.分数：$y=\\frac{x}{x^2}$  \n",
    "6.加帽：帽子有很多，`\\hat{A}`,`\\widehat{A}`,`\\tilde{A}`，$\\hat{A}$，$\\widehat{A}$，$\\tilde{A}$  \n",
    "# 微信公众号使用Markdown，LaTex\n",
    "---\n",
    "找一个在线Markdown编辑器，将Markdown文本复制，粘贴后，能看见预览，在预览侧点击复制，在粘贴到公众号图文编辑里面就好了。  \n",
    "目前这个[Md2All](http://md.aclickall.com/)能很好的转换md,latex公式到微信公众号。\n",
    "Md2All其实是将公式全部转换为图片，然后上传的，经常会有失败，可以先将转换好的图片保存在素材库，直接引用素材库的图片就好了。\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
